#!/bin/bash

# this script installs RemoteGPIO v4.0 following SetupHelper rules (https://github.com/kwindrem/SetupHelper)
#
# this script will accept the following commands on the command line:
#	setup install
#	setup uninstall

packageLogFile="/var/log/RemoteGPIO/current"

#### following lines incorporate helper resources into this script
pkgDir=$( dirname $0 )
pkgName=$( basename $pkgDir )
pkgRoot=$( dirname $pkgDir )
if [ -e "$pkgDir/HelperResources/IncludeHelpers" ]; then
	source "$pkgDir/HelperResources/IncludeHelpers"
elif [ -e "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers" ]; then
	source "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers"
else
	echo "$pkgName: helper files not found - can't continue" | tee -a "/data/log/SetupHelper"
	exit 1
fi
#### end of lines to include helper resources

# GitHub account info - fill in as appropriate
# to include this package in SetupHelper automatic updates

packageGitHubUser="Lucifer06"
packageGitHubBranch="beta"


#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	echo
	echo "The RemoteGPIO is adding external Relays and Digital Inputs"
	echo "with Dingtian IOT Relay devices connected with MQTT"
	echo
	standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
	logMessage "++ Installing RemoteGPIO"

	##
	## Install the services for reboot resiliancy
	#############################################
#installService /data/RemoteGPIO/service/setup_rgpio
#	ln -s /data/RemoteGPIO/service/setup_rgpio/ /service
#	ln -s /data/RemoteGPIO/service/dingtian_mqtt_bridge/ /service
#	ln -s /data/RemoteGPIO/service/dbus-rgpio/ /service

#	svc -u /service/setup_rgpio
#	svc -u /service/dingtian_mqtt_bridge
#	svc -u /service/dbus-rgpio
		

	logMessage "++ $packageName installed"
fi

# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling RemoteGPIO"

#	svc -d /service/dbus-rgpio
#	svc -d /service/setup_rgpio
#	svc -d /service/dingtian_mqtt_bridge

#	rm /service/setup_rgpio
#	rm /service/dingtian_mqtt_bridge
#	rm /service/dbus-rgpio
		
	logMessage "++ $packageName uninstalled"
fi


logMessage "completed"
	
# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript INSTALL_FILES ADD_DBUS_SETTINGS INSTALL_SERVICES