#!/bin/bash

# this script installs RemoteGPIO v3.0 following SetupHelper rules (https://github.com/kwindrem/SetupHelper)
#
# this script will accept the following commands on the command line:
#	setup install
#	setup uninstall

packageLogFile="/var/log/RemoteGPIO/current"

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.

source "/data/SetupHelper/CommonResources"

#### end of lines to include SetupHelper

# GitHub account info - fill in as appropriate
# to include this package in SetupHelper automatic updates
packageGitHubUser="Lucifer06"
packageGitHubBranch="beta-3.0"


#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	echo
	echo "The RemoteGPIO is adding external Relays and Digital Inputs"
	echo "with Dingtian IOT Relay devices either connected via USB or TCP"
	echo
	standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
	logMessage "++ Installing RemoteGPIO"

	##
	## Prepare the devices in /data/RemoteGPIO/sys and conf folder
	##############################################################
	tar -xvf /data/RemoteGPIO/FileSets/VersionIndependent/sys.tar.gz -C /data/RemoteGPIO/
	tar -xvf /data/RemoteGPIO/FileSets/VersionIndependent/bin.tar.gz -C /data/RemoteGPIO/
	mkdir /data/RemoteGPIO/conf
	chmod 777 /data/RemoteGPIO/conf
	touch /data/RemoteGPIO/conf/units.conf
	chmod 666 /data/RemoteGPIO/conf/units.conf
	echo "0" > /data/RemoteGPIO/conf/units.conf

	updateActiveFile /opt/victronenergy/dbus-systemcalc-py/delegates/relaystate.py 
	updateActiveFile /etc/venus/gpio_list
	updateActiveFile /etc/udev/rules.d/serial-starter.rules
	
	##
	## For Large Image only with Node-Red support
	#############################################
	if [ $(dbus -y com.victronenergy.settings /Settings/System/ImageType GetValue) == 1 ]
	then
		updateActiveFile /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json
	fi

	##
	## Install RemoteGPIO GUI Pages
	###############################
	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsIo.qml
	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsRGPIO.qml 
	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit1.qml
	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit2.qml
	updateActiveFile /opt/victronenergy/gui/qml/MbItemDigitalInput.qml

	##
	## Create D-Bus entries for RemoteGPIO
	######################################
	echo "Be patient, creating D-Bus entries..."
	/data/RemoteGPIO/tools/createDbusIntSetting /Settings/Services/RemoteGPIO 
	/data/RemoteGPIO/tools/createDbusIntSetting /Settings/RemoteGPIO/NumberUnits
	/data/RemoteGPIO/tools/createDbusRealSetting /Settings/RemoteGPIO/Latency
	/data/RemoteGPIO/tools/createDbusStringSetting /Settings/RemoteGPIO/Unit1/IP
	/data/RemoteGPIO/tools/createDbusIntSetting /Settings/RemoteGPIO/Unit1/Reboot
	/data/RemoteGPIO/tools/createDbusStringSetting /Settings/RemoteGPIO/Unit2/IP
	/data/RemoteGPIO/tools/createDbusIntSetting /Settings/RemoteGPIO/Unit2/Reboot
	/data/RemoteGPIO/tools/createDbusIntSetting /Settings/RemoteGPIO/Unit1/Protocol
	/data/RemoteGPIO/tools/createDbusIntSetting /Settings/RemoteGPIO/Unit2/Protocol
	/data/RemoteGPIO/tools/createDbusStringSetting /Settings/RemoteGPIO/Unit1/USB_Port
	/data/RemoteGPIO/tools/createDbusStringSetting /Settings/RemoteGPIO/Unit2/USB_Port
	/data/RemoteGPIO/tools/createDbusIntSetting /Settings/Watchdog/RemoteGPIO

	##
	## Install and launch RemoteGPIO Services
	#########################################
	
	ln -sf /data/RemoteGPIO/service/rgpio /service/rgpio
	ln -sf /data/RemoteGPIO/FileSets/VersionIndependent/S90rgpio_pins.sh /etc/rcS.d/S90rgpio_pins.sh
	kill $(ps | grep '{rgpio_driver}' | grep -v grep | awk '{print $1}') 2>/dev/null
	/etc/rcS.d/S90rgpio_pins.sh
	
#	restartSystemCalc=true
	restartGui=true

	# Restarting the below services myself as it seems PackageManager don't do it automatically...
#	svc -t /service/dbus-systemcalc-py
#	svc -t /service/dbus-digitalinputs
	#svc -t /service/start-gui

	logMessage "++ $packageName installed"
fi


# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling RemoteGPIO"

	svc -d /service/rgpio
	kill $(ps | grep '{rgpio_service}' | grep -v grep | awk '{print $1}') 2>/dev/null
	
	restoreActiveFile /opt/victronenergy/dbus-systemcalc-py/delegates/relaystate.py 
	restoreActiveFile /etc/venus/gpio_list
	restoreActiveFile /etc/udev/rules.d/serial-starter.rules
	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsIo.qml
#	rm -f /opt/victronenergy/gui/qml/PageSettingsRGPIO.qml
#	rm -f /opt/victronenergy/gui/qml/PageSettingsUnit1.qml
#	rm -f /opt/victronenergy/gui/qml/PageSettingsUnit2.qml
	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsRGPIO.qml
	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit1.qml
	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit2.qml
	
	rm -f /etc/rcS.d/S90rgpio_pins.sh


	##
	## For Large Image only with Node-Red support
	#############################################
	if [ $(dbus -y com.victronenergy.settings /Settings/System/ImageType GetValue) == 1 ]
	then
		restoreActiveFile /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json
	fi


	##
	## Delete devices
	#################	
	rm -f /dev/gpio/relay_3
	rm -f /dev/gpio/relay_4
	rm -f /dev/gpio/relay_5
	rm -f /dev/gpio/relay_6
	rm -f /dev/gpio/relay_7
	rm -f /dev/gpio/relay_8
	rm -f /dev/gpio/relay_9
	rm -f /dev/gpio/relay_a
	rm -f /dev/gpio/relay_b
	rm -f /dev/gpio/relay_c
	rm -f /dev/gpio/relay_d
	rm -f /dev/gpio/relay_e
	rm -f /dev/gpio/relay_f
	rm -f /dev/gpio/relay_g
	rm -f /dev/gpio/relay_h
	rm -f /dev/gpio/relay_i
	rm -f /dev/gpio/digital_input_5
	rm -f /dev/gpio/digital_input_6
	rm -f /dev/gpio/digital_input_7
	rm -f /dev/gpio/digital_input_8
	rm -f /dev/gpio/digital_input_9
	rm -f /dev/gpio/digital_input_a
	rm -f /dev/gpio/digital_input_b
	rm -f /dev/gpio/digital_input_c
	rm -f /dev/gpio/digital_input_d
	rm -f /dev/gpio/digital_input_e
	rm -f /dev/gpio/digital_input_f
	rm -f /dev/gpio/digital_input_g
	rm -f /dev/gpio/digital_input_h
	rm -f /dev/gpio/digital_input_i
	rm -f /dev/gpio/digital_input_j
	rm -f /dev/gpio/digital_input_k
	
	rm -f /service/rgpio
	rm -Rf /data/RemoteGPIO/conf
	
	##
	## Delete D-Bus entries
	#######################
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/Services/RemoteGPIO
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/RemoteGPIO/NumberUnits
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/RemoteGPIO/Latency
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/RemoteGPIO/Unit1/IP
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/RemoteGPIO/Unit1/Reboot
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/RemoteGPIO/Unit2/IP
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/RemoteGPIO/Unit2/Reboot
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/RemoteGPIO/Unit1/Protocol
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/RemoteGPIO/Unit2/Protocol
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/RemoteGPIO/Unit1/USB_Port
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/RemoteGPIO/Unit2/USB_Port
	/data/RemoteGPIO/tools/updateDbusRemoveSettings /Settings/Watchdog/RemoteGPIO
	
	restartSystemCalc=true
		
	logMessage "++ $packageName uninstalled"
fi



if $filesUpdated ; then
    ##
    ## Reboot or restart the services
    ##
	#svc -d /service/dbus-systemcalc-py/ ; svc -u /service/dbus-systemcalc-py/
	#svc -d /service/gui ; svc -u /service/gui
	#svc -d /service/node-red-venus ; svc -u /service/node-red-venus
    restartGui=true
fi

#if $restartSystemCalc ; then
#	logMessage "restarting systemcalc"
#	svc -t /service/dbus-systemcalc-py
	svc -t /service/dbus-digitalinputs
#fi

logMessage "completed"
	
# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript

