#!/bin/sh
echo "*** starting RemoteGPIO Dingtian Module (dingtian_mqtt_bridge) ***"
exec 2>&1
. /etc/profile.d/profile.sh
# Attend que le port 1883 soit en écoute (LISTEN), ce qui indique que le broker MQTT est prêt.
echo "Waiting for local MQTT broker on port 1883..."
while ! netstat -an | grep ':1883' | grep 'LISTEN'; do
  sleep 1
done
# Attend que le service setup_rgpio soit démarré (up) depuis au moins 5 secondes.
echo "Waiting for setup_rgpio service to be up for at least 5 seconds..."
while [ "$(svstat /service/setup_rgpio/ | awk '{if ($2 == "up") print $5; else print 0}')" -lt 5 ]; do
  sleep 1
done
echo "MQTT broker is available. Starting dbus-rgpio.py..."
exec softlimit -d 100000000 -s 1000000 -a 100000000 /data/RemoteGPIO/modules/dingtian_mqtt_bridge.py
