#!/bin/sh
echo "*** starting RemoteGPIO Dingtian Module (dingtian_mqtt_bridge) ***"
exec 2>&1
. /etc/profile.d/profile.sh
exec softlimit -d 100000000 -s 1000000 -a 100000000 /data/RemoteGPIO/modules/dingtian_mqtt_bridge.py
