#!/bin/bash

# Credits goes to Kwindrem with the DbusSettingsResources for SetupHelper

# addAllDbusSettings adds settings from DbusRemoteGPIOList in the package directory
# the format of each line is:
# {"path":"/Settings/GuiMods/ShortenTankNames", "default":1, "min":0, "max":1}
# min and max are optional

scriptDir="/data/RemoteGPIO/Workinprogress/FileSets/Shared"

if [ -f "$scriptDir/DbusRemoteGPIOList" ]; then
	while read -r line || [[ -n "$line" ]]; do
		settings+="$line, "
	done < "$scriptDir/DbusSettingsList"

	dbus -y com.victronenergy.settings / AddSettings "%[ $settings  ]" &> /dev/null
fi

