#!/bin/bash

#
# $1 is the path to the setting starting with /Settings
# $2 is the new value
#

dbus -y com.victronenergy.settings / AddSettings "%[ {\"path\":\"$1\", \"default\":\"\"} ]" &> /dev/null

#    dbus -y com.victronenergy.settings "$1" SetValue "$2" &> 

