#!/bin/bash

#
# $1 is the path to the setting starting with /Settings
# $2 is the new value
#
# if the setting does not yet exist, it is created, then updated to the new value


echo "removing dbus Settings $@"
    settings=$(echo "$@" | sed -e s_^_\"_ -e s_\$_\"_ -e s_\ _'", "'_g)
echo $settings
    dbus -y com.victronenergy.settings / RemoveSettings "%[ $settings ]" &> /dev/null

