#!/bin/bash

#
# $1 is the path to the setting starting with /Settings
# $2 is the new value
#
# if the setting does not yet exist, it is created, then updated to the new value


    dbus-send --system --print-reply=literal --dest=com.victronenergy.settings "$1"\
            com.victronenergy.BusItem.GetValue 
    if (( $? != 0 )); then
        logMessage "creating dbus Setting $1"
        dbus -y com.victronenergy.settings / AddSettings "%[ {\"path\":\"$1\", \"default\":\"\"} ]" 
    fi

#    dbus -y com.victronenergy.settings "$1" SetValue "$2" &> 

